/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/

"use strict";
var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);

// main.ts
var main_exports = {};
__export(main_exports, {
  default: () => AxiomPlugin
});
module.exports = __toCommonJS(main_exports);
var import_obsidian = require("obsidian");
var VIEW_TYPE_AXIOM = "axiom-view";
var AxiomView = class extends import_obsidian.ItemView {
  constructor(leaf) {
    super(leaf);
  }
  getViewType() {
    return VIEW_TYPE_AXIOM;
  }
  getDisplayText() {
    return "Axiom 3D Mind Map";
  }
  getIcon() {
    return "globe";
  }
  async onOpen() {
    const container = this.contentEl;
    container.empty();
    container.addClass("axiom-view-container");
    const frame = container.createEl("iframe");
    frame.addClass("axiom-iframe");
    frame.setAttr("src", "https://axiom-87ac8.web.app/app.html");
    frame.setAttr("sandbox", "allow-scripts allow-same-origin allow-popups allow-forms allow-popups-to-escape-sandbox allow-presentation");
    frame.style.width = "100%";
    frame.style.height = "100%";
    frame.style.border = "none";
  }
  async onClose() {
  }
};
var AxiomPlugin = class extends import_obsidian.Plugin {
  async onload() {
    this.registerView(
      VIEW_TYPE_AXIOM,
      (leaf) => new AxiomView(leaf)
    );
    this.addRibbonIcon("globe", "Open Axiom 3D Mind Map", (evt) => {
      this.activateView();
    });
    this.addCommand({
      id: "open-axiom-mind-map",
      name: "Open Axiom 3D Mind Map",
      callback: () => {
        this.activateView();
      }
    });
  }
  onunload() {
  }
  async activateView() {
    const { workspace } = this.app;
    let leaf = null;
    const leaves = workspace.getLeavesOfType(VIEW_TYPE_AXIOM);
    if (leaves.length > 0) {
      leaf = leaves[0];
    } else {
      const rightLeaf = workspace.getRightLeaf(false);
      if (rightLeaf) {
        leaf = rightLeaf;
        await leaf.setViewState({ type: VIEW_TYPE_AXIOM, active: true });
      }
    }
    if (leaf) {
      workspace.revealLeaf(leaf);
    }
  }
};
